version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env

  nginx:
      image: nginx:latest
      volumes: 
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80